### ISSUE TITLE
Add instructions to install m4 before running make

### ISSUE THREAD

**Issue by joaopaulosm** [icshwi/e3-base#1]
Some systems might not have **m4** package installed by default, which will cause an error when running `make prepare`. Perhaps is a good idea to add a reminder to install it on the README page.

**Comment by jeonghanlee** [comment]
I am thinking that we need the preparation scripts to install all required packages for EPICS base, and others E3 modules with the automatic switch between Debian and Redhat distribution. I will put m4 package in that script later.

**Comment by jeonghanlee** [comment]
Started to work with scripts directory based on my old scripts, However, it would be better to keep the separated repository and submodules, because it can be extended to be generic package automation scripts

**Comment by jeonghanlee** [comment]
with commit f23b08d , I added the pkg automation *independent* repository in submodule. So, 
```
make pkgs
```
will do the dirty work for us.
